[article]
language_list = [ "简体中文", "繁体中文", "英语", "日语", "泰语", "德语", "法语", "俄语", "韩国语", "越南语", "意大利语", "阿拉伯语", "西班牙语", "孟加拉语", "葡萄牙语", "印地语（北印度语）",]
language = "简体中文"
token = 600
view = "视频作者"
temp = 0.8
index = [ 2, 4,]
time = 1
